import { createSeoMetadata, seoAlternates } from "../../seo";
import { SiteFooterEn } from "../../../components/layout/SiteFooterEn";
import { SiteHeaderEn } from "../../../components/layout/SiteHeaderEn";

export const metadata = createSeoMetadata({
  title: "Privacy Policy | SERPAKOWSKI Nieruchomości",
  description: "Privacy Policy of SERPAKOWSKI Nieruchomości: information about the data controller, personal data processing, contact forms and user rights.",
  canonicalPath: "/en/privacy",
  languages: seoAlternates.privacy,
  locale: "en_US",
});

export default function PrivacyPageEn() {
  return (
    <div className="min-h-screen bg-[#0C2D3A] text-neutral-100">
      <SiteHeaderEn />
      <main className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8 pt-28 pb-20">
        <section className="rounded-3xl bg-white/5 p-7 sm:p-10 ring-1 ring-white/10 shadow-[0_20px_60px_rgba(0,0,0,0.35)]">
          <h1 className="font-serif text-3xl sm:text-4xl text-white">Privacy Policy</h1>
          <p className="mt-3 text-sm text-neutral-300">Last updated: 30.04.2026</p>
          <p className="mt-6 text-neutral-200/90 leading-relaxed">
            This Privacy Policy explains how SERPAKOWSKI Nieruchomości processes personal data of website users, people who contact us through contact forms, and people who use available communication channels.
          </p>
          <div className="mt-10 space-y-9 text-neutral-200/90">
            <section><h2 className="font-serif text-2xl text-white mb-3">1. Data controller</h2><p>The data controller is Serhii Kovlak, conducting business under the brand SERPAKOWSKI Nieruchomości, correspondence address: Złota 75A/7, 00-819 Warsaw, Poland, NIP: 1133184502, REGON: 543202915.</p><p className="mt-3">You can contact the controller via:</p><ul className="mt-2 list-disc pl-6 space-y-1"><li>e-mail: kontakt@serpakowski.pl</li><li>phone: +48 453 053 969</li></ul></section>
            <section><h2 className="font-serif text-2xl text-white mb-3">2. Scope of processed data</h2><p>Depending on how you use the website, we may process the following data:</p><ul className="mt-2 list-disc pl-6 space-y-1"><li>first name,</li><li>phone number,</li><li>e-mail address, if provided,</li><li>message content or inquiry description,</li><li>information related to searching for, renting, letting, selling or buying real estate,</li><li>information provided in correspondence,</li><li>technical data related to website use, such as IP address, browser and device information, date and time of visit, and cookies.</li></ul></section>
            <section><h2 className="font-serif text-2xl text-white mb-3">3. Purposes of data processing</h2><p>Personal data may be processed for the following purposes:</p><ul className="mt-2 list-disc pl-6 space-y-1"><li>handling inquiries submitted through contact forms,</li><li>contact by phone, e-mail or messengers,</li><li>preparing a response, offer, or cooperation proposal,</li><li>serving clients interested in rental, letting, purchase, or sale of real estate,</li><li>handling B2B contacts and partnership cooperation,</li><li>ensuring proper operation and security of the website,</li><li>analyzing website usage and carrying out marketing activities — only where user consent is required and such consent has been granted,</li><li>establishing, pursuing, or defending potential claims.</li></ul></section>
            <section><h2 className="font-serif text-2xl text-white mb-3">4. Legal bases for processing</h2><p>Data is processed based on:</p><ul className="mt-2 list-disc pl-6 space-y-1"><li>Article 6(1)(b) GDPR/RODO — where processing is necessary to take steps at the request of the data subject prior to entering into a contract, or to perform a contract,</li><li>Article 6(1)(f) GDPR/RODO — the controller’s legitimate interest, such as handling correspondence, contacting users, website security, protection against claims, and business development,</li><li>Article 6(1)(a) GDPR/RODO — user consent, in particular for certain cookies, analytics, marketing tools, or voluntary marketing consents, if implemented.</li></ul></section>
            <section><h2 className="font-serif text-2xl text-white mb-3">5. Contact forms</h2><p>The website may contain contact forms. Providing data in a form is voluntary, but necessary to handle your inquiry.</p><p className="mt-3">Data from the form may include first name, phone number, message content, website language, source page URL, and submission date.</p><p className="mt-3">Contact forms may be technically handled by Formspree. Data provided in the form may be transferred to Formspree for technical handling of the inquiry and forwarding to the controller. Inquiries may then be forwarded to the controller via e-mail or notifications, e.g., Telegram.</p></section>
            <section><h2 className="font-serif text-2xl text-white mb-3">6. Contact via messengers</h2><p>If you contact us via Telegram, WhatsApp, Viber, or another messenger, data provided in that communication is processed to handle contact and respond to your inquiry.</p><p className="mt-3">Use of messengers is also governed by the privacy policies of those service providers.</p></section>
            <section><h2 className="font-serif text-2xl text-white mb-3">7. Hosting, email and technical support</h2><p>The website may be technically supported by external service providers, in particular:</p><ul className="mt-2 list-disc pl-6 space-y-1"><li>website hosting provider,</li><li>e-mail provider,</li><li>contact form provider,</li><li>analytics or marketing tool providers, if implemented and if the user gives the appropriate consent.</li></ul><p className="mt-3">In particular, the website may use services such as Vercel, Formspree, and home.pl to the extent necessary for website operation, form handling, and communication.</p></section>
            <section><h2 className="font-serif text-2xl text-white mb-3">8. Cookies</h2><p>The website may use cookies and similar technologies.</p><p className="mt-3">Cookies may be used in particular to:</p><ul className="mt-2 list-disc pl-6 space-y-1"><li>ensure proper website operation,</li><li>remember user preferences,</li><li>collect statistics and analytics,</li><li>carry out marketing and remarketing activities, if such tools are implemented.</li></ul><p className="mt-3">Cookies necessary for website operation may be used without separate user consent. Analytics, marketing, or other optional cookies will be used only in accordance with applicable law and after obtaining required user consent, where such consent is required.</p><p className="mt-3">Detailed information on cookies may be described in a separate cookie policy in the future.</p></section>
            <section><h2 className="font-serif text-2xl text-white mb-3">9. Analytics and marketing tools</h2><p>The website may in the future use analytics or marketing tools such as Google Analytics, Google Ads, Meta Pixel, or similar solutions.</p><p className="mt-3">Such tools will be activated only to the extent compliant with applicable law, in particular after obtaining appropriate user consent where consent is required.</p></section>
            <section><h2 className="font-serif text-2xl text-white mb-3">10. Data recipients</h2><p>Personal data may be transferred to entities that support the controller in operating the website and handling contact, in particular:</p><ul className="mt-2 list-disc pl-6 space-y-1"><li>hosting and technical infrastructure providers,</li><li>e-mail providers,</li><li>contact form providers,</li><li>analytics and marketing tool providers, if implemented in compliance with the law,</li><li>entities providing legal, accounting, or administrative services, where necessary,</li><li>public authorities, if the obligation to disclose data results from legal provisions.</li></ul></section>
            <section><h2 className="font-serif text-2xl text-white mb-3">11. Transfers of data outside the EEA</h2><p>Some service providers used by the website may process data outside the European Economic Area.</p><p className="mt-3">In such cases, data transfers are carried out based on appropriate legal mechanisms provided by GDPR/RODO, such as standard contractual clauses or other safeguards required by law.</p></section>
            <section><h2 className="font-serif text-2xl text-white mb-3">12. Data retention period</h2><p>Data from contact forms and correspondence is stored for the period necessary to handle the inquiry, and then no longer than 12 months, unless longer retention is required by law or justified by protection against claims.</p><p className="mt-3">If a contract is concluded or cooperation starts, data may be stored for the period required by law, in particular tax, accounting, or claims-related regulations.</p></section>
            <section><h2 className="font-serif text-2xl text-white mb-3">13. User rights</h2><p>The data subject has the right to:</p><ul className="mt-2 list-disc pl-6 space-y-1"><li>access their data,</li><li>rectify data,</li><li>erase data,</li><li>restrict processing,</li><li>object to processing,</li><li>data portability,</li><li>withdraw consent to the extent processing is based on consent,</li><li>lodge a complaint with the President of the Personal Data Protection Office (Prezes Urzędu Ochrony Danych Osobowych).</li></ul><p className="mt-3">To exercise your rights, you can contact the controller at: kontakt@serpakowski.pl.</p></section>
            <section><h2 className="font-serif text-2xl text-white mb-3">14. Voluntary provision of data</h2><p>Providing data is voluntary, but it may be necessary to handle your inquiry, prepare a response, contact you, or carry out cooperation.</p></section>
            <section><h2 className="font-serif text-2xl text-white mb-3">15. Changes to this Privacy Policy</h2><p>This Privacy Policy may be updated, in particular in the event of changes to website operations, implementation of new tools, or changes in legal regulations.</p><p className="mt-3">The current version of this Privacy Policy is always available on the website.</p><p className="mt-3">Area of operation: Warsaw, Poland.</p></section>
          </div>
        </section>
      </main>
      <SiteFooterEn />
    </div>
  );
}
