import { createSeoMetadata, seoAlternates } from "../../seo";
import { SiteFooterPl } from "../../../components/layout/SiteFooterPl";
import { SiteHeaderPl } from "../../../components/layout/SiteHeaderPl";

export const metadata = createSeoMetadata({
  title: "Polityka prywatności | SERPAKOWSKI Nieruchomości",
  description: "Polityka prywatności SERPAKOWSKI Nieruchomości: informacje o administratorze danych, zakresie przetwarzania danych, formularzach kontaktowych i prawach użytkownika.",
  canonicalPath: "/pl/polityka-prywatnosci",
  languages: seoAlternates.privacy,
  locale: "pl_PL",
});

export default function PolitykaPrywatnosciPage() {
  return (
    <div className="min-h-screen bg-[#0C2D3A] text-neutral-100">
      <SiteHeaderPl />
      <main className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8 pt-28 pb-20">
        <section className="rounded-3xl bg-white/5 p-7 sm:p-10 ring-1 ring-white/10 shadow-[0_20px_60px_rgba(0,0,0,0.35)]">
          <h1 className="font-serif text-3xl sm:text-4xl text-white">Polityka prywatności</h1>
          <p className="mt-3 text-sm text-neutral-300">Ostatnia aktualizacja: 30.04.2026</p>
          <p className="mt-6 text-neutral-200/90 leading-relaxed">
            Niniejsza polityka prywatności wyjaśnia, w jaki sposób SERPAKOWSKI Nieruchomości przetwarza dane osobowe użytkowników strony internetowej, osób kontaktujących się za pomocą formularzy oraz osób korzystających z dostępnych kanałów kontaktu.
          </p>
          <div className="mt-10 space-y-9 text-neutral-200/90">
            <section><h2 className="font-serif text-2xl text-white mb-3">1. Administrator danych</h2><p>Administratorem danych osobowych jest Serhii Kovlak, prowadzący działalność pod marką SERPAKOWSKI Nieruchomości, z adresem do korespondencji: Złota 75A/7, 00-819 Warszawa, Polska, NIP: 1133184502, REGON: 543202915.</p><p className="mt-3">Kontakt z administratorem jest możliwy:</p><ul className="mt-2 list-disc pl-6 space-y-1"><li>e-mail: kontakt@serpakowski.pl</li><li>telefon: +48 453 053 969</li></ul></section>
            <section><h2 className="font-serif text-2xl text-white mb-3">2. Zakres przetwarzanych danych</h2><p>W zależności od sposobu korzystania ze strony możemy przetwarzać następujące dane:</p><ul className="mt-2 list-disc pl-6 space-y-1"><li>imię,</li><li>numer telefonu,</li><li>adres e-mail, jeżeli zostanie podany,</li><li>treść wiadomości lub opis zgłoszenia,</li><li>informacje dotyczące poszukiwania, wynajmu, sprzedaży lub zakupu nieruchomości,</li><li>informacje przekazane w ramach korespondencji,</li><li>dane techniczne związane z korzystaniem ze strony, takie jak adres IP, informacje o przeglądarce, urządzeniu, data i godzina wizyty oraz pliki cookies.</li></ul></section>
            <section><h2 className="font-serif text-2xl text-white mb-3">3. Cele przetwarzania danych</h2><p>Dane osobowe mogą być przetwarzane w następujących celach:</p><ul className="mt-2 list-disc pl-6 space-y-1"><li>obsługa zapytań przesłanych przez formularze kontaktowe,</li><li>kontakt telefoniczny, mailowy lub przez komunikatory,</li><li>przygotowanie odpowiedzi, oferty lub propozycji współpracy,</li><li>obsługa klientów zainteresowanych najmem, wynajmem, zakupem lub sprzedażą nieruchomości,</li><li>obsługa kontaktów B2B i współpracy partnerskiej,</li><li>zapewnienie prawidłowego działania i bezpieczeństwa strony,</li><li>analiza sposobu korzystania ze strony oraz działania marketingowe — wyłącznie wtedy, gdy wymagane jest uzyskanie zgody użytkownika i taka zgoda została udzielona,</li><li>dochodzenie lub obrona ewentualnych roszczeń.</li></ul></section>
            <section><h2 className="font-serif text-2xl text-white mb-3">4. Podstawy prawne przetwarzania</h2><p>Dane są przetwarzane na podstawie:</p><ul className="mt-2 list-disc pl-6 space-y-1"><li>art. 6 ust. 1 lit. b RODO — gdy przetwarzanie jest potrzebne do podjęcia działań na żądanie osoby, której dane dotyczą, przed zawarciem umowy lub do wykonania umowy,</li><li>art. 6 ust. 1 lit. f RODO — prawnie uzasadniony interes administratora, taki jak obsługa korespondencji, kontakt z użytkownikiem, bezpieczeństwo strony, ochrona przed roszczeniami oraz rozwój działalności,</li><li>art. 6 ust. 1 lit. a RODO — zgoda użytkownika, w szczególności w przypadku niektórych cookies, narzędzi analitycznych, marketingowych lub dobrowolnych zgód marketingowych, jeżeli zostaną wdrożone.</li></ul></section>
            <section><h2 className="font-serif text-2xl text-white mb-3">5. Formularze kontaktowe</h2><p>Na stronie mogą znajdować się formularze kontaktowe. Podanie danych w formularzu jest dobrowolne, ale niezbędne do obsługi zgłoszenia.</p><p className="mt-3">Dane z formularza mogą obejmować imię, numer telefonu, treść wiadomości, język strony, adres strony źródłowej oraz datę wysłania zgłoszenia.</p><p className="mt-3">Formularze kontaktowe mogą być obsługiwane technicznie przez Formspree. Dane podane w formularzu mogą być przekazywane do Formspree w celu technicznej obsługi zgłoszenia i przekazania go administratorowi. Zgłoszenia mogą być następnie przekazywane administratorowi za pośrednictwem poczty e-mail lub powiadomień, np. Telegram.</p></section>
            <section><h2 className="font-serif text-2xl text-white mb-3">6. Kontakt przez komunikatory</h2><p>Jeżeli użytkownik kontaktuje się z nami przez Telegram, WhatsApp, Viber lub inny komunikator, dane przekazane w ramach takiej komunikacji są przetwarzane w celu obsługi kontaktu i odpowiedzi na zapytanie.</p><p className="mt-3">Korzystanie z komunikatorów podlega również zasadom prywatności dostawców tych usług.</p></section>
            <section><h2 className="font-serif text-2xl text-white mb-3">7. Hosting, poczta i obsługa techniczna</h2><p>Strona internetowa może być obsługiwana technicznie przez zewnętrznych dostawców usług, w szczególności:</p><ul className="mt-2 list-disc pl-6 space-y-1"><li>dostawcę hostingu strony,</li><li>dostawcę poczty e-mail,</li><li>dostawcę formularzy kontaktowych,</li><li>dostawców narzędzi analitycznych lub marketingowych, jeżeli zostaną wdrożone i użytkownik wyrazi odpowiednią zgodę.</li></ul><p className="mt-3">W szczególności strona może korzystać z usług takich jak Vercel, Formspree oraz home.pl w zakresie niezbędnym do działania strony, obsługi formularzy i komunikacji.</p></section>
            <section><h2 className="font-serif text-2xl text-white mb-3">8. Cookies</h2><p>Strona może korzystać z plików cookies i podobnych technologii.</p><p className="mt-3">Cookies mogą być wykorzystywane w szczególności do:</p><ul className="mt-2 list-disc pl-6 space-y-1"><li>zapewnienia prawidłowego działania strony,</li><li>zapamiętania preferencji użytkownika,</li><li>prowadzenia statystyk i analityki,</li><li>prowadzenia działań marketingowych i remarketingowych, jeżeli takie narzędzia zostaną wdrożone.</li></ul><p className="mt-3">Cookies niezbędne do działania strony mogą być stosowane bez osobnej zgody użytkownika. Cookies analityczne, marketingowe lub inne opcjonalne będą stosowane wyłącznie zgodnie z obowiązującymi przepisami i po uzyskaniu wymaganej zgody użytkownika, jeżeli taka zgoda jest wymagana.</p><p className="mt-3">Szczegółowe informacje dotyczące cookies mogą zostać opisane w odrębnej polityce cookies.</p></section>
            <section><h2 className="font-serif text-2xl text-white mb-3">9. Narzędzia analityczne i marketingowe</h2><p>Strona może w przyszłości korzystać z narzędzi analitycznych lub marketingowych, takich jak Google Analytics, Google Ads, Meta Pixel lub podobne rozwiązania.</p><p className="mt-3">Takie narzędzia będą uruchamiane wyłącznie w zakresie zgodnym z obowiązującymi przepisami, w szczególności po uzyskaniu odpowiedniej zgody użytkownika, jeżeli zgoda jest wymagana.</p></section>
            <section><h2 className="font-serif text-2xl text-white mb-3">10. Odbiorcy danych</h2><p>Dane osobowe mogą być przekazywane podmiotom, które wspierają administratora w prowadzeniu strony i obsłudze kontaktu, w szczególności:</p><ul className="mt-2 list-disc pl-6 space-y-1"><li>dostawcom hostingu i infrastruktury technicznej,</li><li>dostawcom poczty e-mail,</li><li>dostawcom formularzy kontaktowych,</li><li>dostawcom narzędzi analitycznych i marketingowych, jeżeli zostaną wdrożone zgodnie z przepisami,</li><li>podmiotom świadczącym usługi prawne, księgowe lub administracyjne, jeżeli jest to niezbędne,</li><li>organom publicznym, jeżeli obowiązek przekazania danych wynika z przepisów prawa.</li></ul></section>
            <section><h2 className="font-serif text-2xl text-white mb-3">11. Przekazywanie danych poza EOG</h2><p>Niektórzy dostawcy usług, z których może korzystać strona, mogą przetwarzać dane poza Europejskim Obszarem Gospodarczym.</p><p className="mt-3">W takim przypadku przekazywanie danych odbywa się na podstawie odpowiednich mechanizmów prawnych przewidzianych przez RODO, takich jak standardowe klauzule umowne lub inne zabezpieczenia wymagane przez przepisy prawa.</p></section>
            <section><h2 className="font-serif text-2xl text-white mb-3">12. Okres przechowywania danych</h2><p>Dane z formularzy kontaktowych i korespondencji przechowujemy przez okres niezbędny do obsługi zapytania, a następnie nie dłużej niż 12 miesięcy, chyba że dłuższe przechowywanie jest wymagane przez przepisy prawa lub uzasadnione ochroną przed roszczeniami.</p><p className="mt-3">Jeżeli dojdzie do zawarcia umowy lub współpracy, dane mogą być przechowywane przez okres wymagany przepisami prawa, w szczególności przepisami podatkowymi, księgowymi lub dotyczącymi dochodzenia roszczeń.</p></section>
            <section><h2 className="font-serif text-2xl text-white mb-3">13. Prawa użytkownika</h2><p>Osobie, której dane dotyczą, przysługuje prawo do:</p><ul className="mt-2 list-disc pl-6 space-y-1"><li>dostępu do swoich danych,</li><li>sprostowania danych,</li><li>usunięcia danych,</li><li>ograniczenia przetwarzania,</li><li>sprzeciwu wobec przetwarzania,</li><li>przenoszenia danych,</li><li>cofnięcia zgody w zakresie, w jakim przetwarzanie odbywa się na podstawie zgody,</li><li>wniesienia skargi do Prezesa Urzędu Ochrony Danych Osobowych.</li></ul><p className="mt-3">W celu skorzystania z praw można skontaktować się z administratorem pod adresem: kontakt@serpakowski.pl.</p></section>
            <section><h2 className="font-serif text-2xl text-white mb-3">14. Dobrowolność podania danych</h2><p>Podanie danych jest dobrowolne, ale może być niezbędne do obsługi zapytania, przygotowania odpowiedzi, kontaktu lub realizacji współpracy.</p></section>
            <section><h2 className="font-serif text-2xl text-white mb-3">15. Zmiany polityki prywatności</h2><p>Polityka prywatności może być aktualizowana, w szczególności w przypadku zmian w sposobie działania strony, wdrożenia nowych narzędzi lub zmian przepisów prawa.</p><p className="mt-3">Aktualna wersja polityki prywatności jest zawsze dostępna na stronie internetowej.</p></section>
          </div>
        </section>
      </main>
      <SiteFooterPl />
    </div>
  );
}
